/**
 * Colors.kt
 *
 * Material 3 color definitions for the CryptoVault application.
 * This file contains the complete color palette generated from the seed color,
 * providing all color roles required by Material 3 components.
 *
 * Color palette generated by: https://materialkolor.com
 * Original palette source: https://coolors.co/palette/e63946-f1faee-a8dadc-457b9d-1d3557
 *
 * The palette includes:
 * - Primary colors: Main brand colors and their variants
 * - Secondary colors: Supporting accent colors
 * - Tertiary colors: Additional accent for variety
 * - Error colors: For error states and validation
 * - Surface colors: For backgrounds and containers
 * - Outline colors: For borders and dividers
 *
 * Both light and dark variants are provided for each color role.
 *
 * @see Theme.kt for how these colors are used in the color scheme
 */
package com.example.cryptowallet.theme

import androidx.compose.ui.graphics.Color

/**
 * Seed color used to generate the Material 3 color palette.
 * Based on a deep navy blue (#1D3557).
 */
internal val Seed = Color(0xFF1D3557)

// ============================================================================
// LIGHT THEME COLORS
// ============================================================================

/** Primary color for light theme - muted blue */
internal val PrimaryLight = Color(0xFF485F84)
/** Color for content on primary surfaces in light theme */
internal val OnPrimaryLight = Color(0xFFFFFFFF)
/** Primary container color for light theme */
internal val PrimaryContainerLight = Color(0xFFD5E3FF)
/** Color for content on primary container in light theme */
internal val OnPrimaryContainerLight = Color(0xFF30476A)

/** Secondary color for light theme - teal blue */
internal val SecondaryLight = Color(0xFF2B6485)
/** Color for content on secondary surfaces in light theme */
internal val OnSecondaryLight = Color(0xFFFFFFFF)
/** Secondary container color for light theme */
internal val SecondaryContainerLight = Color(0xFFC7E7FF)
/** Color for content on secondary container in light theme */
internal val OnSecondaryContainerLight = Color(0xFF064C6B)

/** Tertiary color for light theme - teal green */
internal val TertiaryLight = Color(0xFF356668)
/** Color for content on tertiary surfaces in light theme */
internal val OnTertiaryLight = Color(0xFFFFFFFF)
/** Tertiary container color for light theme */
internal val TertiaryContainerLight = Color(0xFFB9ECEE)
/** Color for content on tertiary container in light theme */
internal val OnTertiaryContainerLight = Color(0xFF1A4E50)

/** Error color for light theme - red */
internal val ErrorLight = Color(0xFFBB152C)
/** Color for content on error surfaces in light theme */
internal val OnErrorLight = Color(0xFFFFFFFF)
/** Error container color for light theme */
internal val ErrorContainerLight = Color(0xFFFFDAD8)
/** Color for content on error container in light theme */
internal val OnErrorContainerLight = Color(0xFF410007)

/** Background color for light theme */
internal val BackgroundLight = Color(0xFFF9F9F9)
/** Color for content on background in light theme */
internal val OnBackgroundLight = Color(0xFF1A1C1C)
/** Surface color for light theme */
internal val SurfaceLight = Color(0xFFF9F9F9)
/** Color for content on surface in light theme */
internal val OnSurfaceLight = Color(0xFF1A1C1C)
/** Surface variant color for light theme */
internal val SurfaceVariantLight = Color(0xFFDCE5D9)
/** Color for content on surface variant in light theme */
internal val OnSurfaceVariantLight = Color(0xFF404941)

/** Outline color for light theme - for borders */
internal val OutlineLight = Color(0xFF717970)
/** Outline variant color for light theme */
internal val OutlineVariantLight = Color(0xFFC0C9BE)
/** Scrim color for light theme - for overlays */
internal val ScrimLight = Color(0xFF000000)

/** Inverse surface color for light theme */
internal val InverseSurfaceLight = Color(0xFF2F3131)
/** Color for content on inverse surface in light theme */
internal val InverseOnSurfaceLight = Color(0xFFF0F1F1)
/** Inverse primary color for light theme */
internal val InversePrimaryLight = Color(0xFFB0C7F1)

/** Dim surface color for light theme */
internal val SurfaceDimLight = Color(0xFFDADADA)
/** Bright surface color for light theme */
internal val SurfaceBrightLight = Color(0xFFF9F9F9)
/** Lowest elevation surface container for light theme */
internal val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
/** Low elevation surface container for light theme */
internal val SurfaceContainerLowLight = Color(0xFFF3F3F4)
/** Standard surface container for light theme */
internal val SurfaceContainerLight = Color(0xFFEEEEEE)
/** High elevation surface container for light theme */
internal val SurfaceContainerHighLight = Color(0xFFE8E8E8)
/** Highest elevation surface container for light theme */
internal val SurfaceContainerHighestLight = Color(0xFFE2E2E2)

// ============================================================================
// DARK THEME COLORS
// ============================================================================

/** Primary color for dark theme - light blue */
internal val PrimaryDark = Color(0xFFB0C7F1)
/** Color for content on primary surfaces in dark theme */
internal val OnPrimaryDark = Color(0xFF183153)
/** Primary container color for dark theme */
internal val PrimaryContainerDark = Color(0xFF30476A)
/** Color for content on primary container in dark theme */
internal val OnPrimaryContainerDark = Color(0xFFD5E3FF)

/** Secondary color for dark theme - light teal */
internal val SecondaryDark = Color(0xFF98CDF2)
/** Color for content on secondary surfaces in dark theme */
internal val OnSecondaryDark = Color(0xFF00344C)
/** Secondary container color for dark theme */
internal val SecondaryContainerDark = Color(0xFF064C6B)
/** Color for content on secondary container in dark theme */
internal val OnSecondaryContainerDark = Color(0xFFC7E7FF)

/** Tertiary color for dark theme - light teal green */
internal val TertiaryDark = Color(0xFF9ECFD1)
/** Color for content on tertiary surfaces in dark theme */
internal val OnTertiaryDark = Color(0xFF003739)
/** Tertiary container color for dark theme */
internal val TertiaryContainerDark = Color(0xFF1A4E50)
/** Color for content on tertiary container in dark theme */
internal val OnTertiaryContainerDark = Color(0xFFB9ECEE)

/** Error color for dark theme - light red/pink */
internal val ErrorDark = Color(0xFFFFB3B1)
/** Color for content on error surfaces in dark theme */
internal val OnErrorDark = Color(0xFF680011)
/** Error container color for dark theme */
internal val ErrorContainerDark = Color(0xFF92001C)
/** Color for content on error container in dark theme */
internal val OnErrorContainerDark = Color(0xFFFFDAD8)

/** Background color for dark theme */
internal val BackgroundDark = Color(0xFF121414)
/** Color for content on background in dark theme */
internal val OnBackgroundDark = Color(0xFFE2E2E2)
/** Surface color for dark theme */
internal val SurfaceDark = Color(0xFF121414)
/** Color for content on surface in dark theme */
internal val OnSurfaceDark = Color(0xFFE2E2E2)
/** Surface variant color for dark theme */
internal val SurfaceVariantDark = Color(0xFF404941)
/** Color for content on surface variant in dark theme */
internal val OnSurfaceVariantDark = Color(0xFFC0C9BE)

/** Outline color for dark theme - for borders */
internal val OutlineDark = Color(0xFF8A9389)
/** Outline variant color for dark theme */
internal val OutlineVariantDark = Color(0xFF404941)
/** Scrim color for dark theme - for overlays */
internal val ScrimDark = Color(0xFF000000)

/** Inverse surface color for dark theme */
internal val InverseSurfaceDark = Color(0xFFE2E2E2)
/** Color for content on inverse surface in dark theme */
internal val InverseOnSurfaceDark = Color(0xFF2F3131)
/** Inverse primary color for dark theme */
internal val InversePrimaryDark = Color(0xFF485F84)

/** Dim surface color for dark theme */
internal val SurfaceDimDark = Color(0xFF121414)
/** Bright surface color for dark theme */
internal val SurfaceBrightDark = Color(0xFF37393A)
/** Lowest elevation surface container for dark theme */
internal val SurfaceContainerLowestDark = Color(0xFF0C0F0F)
/** Low elevation surface container for dark theme */
internal val SurfaceContainerLowDark = Color(0xFF1A1C1C)
/** Standard surface container for dark theme */
internal val SurfaceContainerDark = Color(0xFF1E2020)
/** High elevation surface container for dark theme */
internal val SurfaceContainerHighDark = Color(0xFF282A2B)
/** Highest elevation surface container for dark theme */
internal val SurfaceContainerHighestDark = Color(0xFF333535)